name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major or minor)"
        required: true
        default: "minor"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: "release"
          fetch-depth: 0 # Alle Tags und Historie holen

      - name: Set Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: next_version
        run: |
          latest=${{ steps.get_tag.outputs.latest_tag }}
          if [[ -z "$latest" ]]; then
            latest="0.0.0"
          fi
          IFS='.' read -r major minor patch <<< "$latest"
          if [[ "${{ github.event.inputs.release_type }}" == "major" ]]; then
            major=$((major+1))
            minor=0
            patch=0
          else
            minor=$((minor+1))
            patch=0
          fi
          next="$major.$minor.$patch"
          echo "Next version: $next"
          echo "next_version=$next" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.next_version.outputs.next_version }}
          git push origin ${{ steps.next_version.outputs.next_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: ng build

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/join/browser/"
          server-dir: "/angular_projects/join-mmc/"
          protocol: "ftp"
