name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to merge into release'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: 'release'

      - name: Set Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Merge Main into Release
        run: |
          git pull origin main --no-ff --no-edit
          git push

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: ng build

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/join/browser/'
          server-dir: '/angular_projects/join-mmc/'
          protocol: 'ftp'
